version: "3"

services:
  tomcat_jenkins:
    image: tomcat:latest
    container_name: tomcat_jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins.war:/usr/local/tomcat/webapps/jenkins.war
    environment:
      - CATALINA_OPTS=-Djenkins.install.runSetupWizard=false
